



CREATE DATABASE MANAGER_OBJECT;
USE MANAGER_OBJECT;
CREATE TABLE STUDENT(
	MASV NVARCHAR(50) PRIMARY KEY,
	FULLNAME NVARCHAR(50),
	EMAIL NVARCHAR(50),
	PHONENUMBER NVARCHAR(15),
	GENDER BIT ,
	ADDRESS_ST NVARCHAR(50),
	IMAGE_ST NVARCHAR(50)
);

CREATE TABLE GRADE(
ID INT IDENTITY(1,1) PRIMARY KEY,
MASV_FK NVARCHAR(50),
ENGLISH FLOAT,
TINHOC FLOAT,
GDTC FLOAT,
FOREIGN KEY (MASV_FK) REFERENCES STUDENT(MASV)
);

CREATE TABLE USERS(
USERNAME NVARCHAR(50)PRIMARY KEY,
PASSWORDS NVARCHAR(50),
ROLES NVARCHAR(50),
gmail varchar(50),
gender nvarchar(3),
birthday date
);

INSERT INTO USERS(USERNAME , PASSWORDS , ROLES)VALUES
		('TRAN ANH TUAN' , '123' , 'TEACHER'),
		('LE ANH TU' , '1234' , 'GDDT');



go
create trigger deleteSudent 
on student
instead of delete
as
begin
  delete from GRADE where MASV_FK in
 (select MASV from deleted)
 delete from STUDENT where MASV in
 (select MASV from deleted)
end



INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV01' , 'KIEU ANH VAN 0' , 'VAN1@GMAIL.COM' , '0347179445',1 , 'TP.HCM' , 'h3.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV02' , 'KIEU ANH VAN 1' , 'VAN2@GMAIL.COM' , '0847143774',0 , 'TP.HCM' , 'pp.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV03' , 'KIEU ANH VAN 2' , 'VAN3@GMAIL.COM' , '0877179458',1 , 'TP.HCM' , 'h7.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV04' , 'KIEU ANH VAN 3' , 'VAN4@GMAIL.COM' , '0344565558',1 , 'TP.HCM' , 'bleach4.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV05' , 'KIEU ANH VAN 4' , 'VAN5@GMAIL.COM' , '0347657765',0 , 'TP.HCM' , 'h2.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV06' , 'KIEU ANH VAN 0' , 'VAN1@GMAIL.COM' , '0347179445',1 , 'TP.HCM' , 'bleach10.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV07' , 'KIEU ANH VAN 1' , 'VAN2@GMAIL.COM' , '0847143774',1 , 'TP.HCM' , 'IU.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV08' , 'KIEU ANH VAN 2' , 'VAN3@GMAIL.COM' , '0877179458',0 , 'TP.HCM' , 'angeliclayer1.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV09' , 'KIEU ANH VAN 3' , 'VAN4@GMAIL.COM' , '0344565558',1 , 'TP.HCM' , 'beans2.jpg');
INSERT INTO STUDENT(MASV , FULLNAME , EMAIL ,PHONENUMBER ,GENDER , ADDRESS_ST , IMAGE_ST) VALUES
('SV00' , 'KIEU ANH VAN 4' , 'VAN5@GMAIL.COM' , '0347657765',0 , 'TP.HCM' , 'images (2).jpg');



SELECT * FROM STUDENT;
SELECT * FROM GRADE;
SELECT * FROM USERS;